version: "3.8"

services:
  hackathon-mysql:
    image: mysql:8.0
    container_name: hackathon-mysql
    platform: linux/x86_64
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hackathon
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - type: volume
        source: hackathon-mysql-volume
        target: /var/lib/mysql
      - type: bind
        source: ./init
        target: /docker-entrypoint-initdb.d
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/serviceAccountKey.json
    ports:
      - "8080:8080"
    depends_on:
      - hackathon-mysql

volumes:
  hackathon-mysql-volume:
    name: hackathon-mysql-volume