version: "3.8"

services:
  hackathon-mysql:
    container_name: hackathon-mysql
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/x86_64
    tty: true
    ports:
      - 3307:3306
    env_file:
      - ./.env
    volumes:
      - type: volume
        source: hackathon-mysql-volume
        target: /var/lib/mysql
      - type: bind
        source: ./init
        target: /docker-entrypoint-initdb.d
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/serviceAccountKey.json
    ports:
      - "8080:8080"
    depends_on:
      - hackathon-mysql

volumes:
  hackathon-mysql-volume:
    name: hackathon-mysql-volume