on:
    pull_request:
      types: [opened, reopened, ready_for_review]
    issue_comment:
    jobs:
    pr_agent_job:
      if: ${{ github.event.sender.type != 'Bot' }}
      runs-on: ubuntu-latest
      permissions:
        issues: write
        pull-requests: write
        contents: write
      name: Run pr agent on every pull request, respond to user comments
      steps:
        - name: PR Agent action step
          id: pragent
          uses: Codium-ai/pr-agent@main
          env:
            OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            # OpenAIのモデル選択
            config.model: "gpt-3.5-turbo"
            # OpenAIのフォールバックモデル選択
            config.fallback_model: "gpt-3.5-turbo"
            # PRのタイトルも自動生成
            pr_description.generate_ai_title: true
            # PRの説明に追加の指示を記述
            pr_description.extra_instructions: "回答は必ず全て日本語で記述してください。"
            # PRのレビューに追加の指示を記述
            pr_reviewer.extra_instructions: "回答は必ず全て日本語で記述してください。"
            # PRにスコアを付ける
            pr_reviewer.require_score_review: true
            # PRが分割可能か判断する機能を有効化
            pr_reviewer.require_can_be_split_review: true
            # PRの改善提案の追加プロンプト
            pr_code_suggestions.extra_instructions: "回答は必ず全て日本語で記述してください。"
            # 問題点だけにフォーカスするかどうか
            pr_code_suggestions.focus_only_on_problems: false
            # 改善提案にGood/Badの評価をつける
            pr_code_suggestions.allow_thumbs_up_down: true
            # Changelogの自動更新時の追加プロンプト
            pr_update_changelog.extra_instructions: "回答は必ず全て日本語で記述してください。"